apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello.arepasoftware.com
    http:
      paths:
      - backend:
          serviceName: hello-v1-svc
          servicePort: 80