apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issue-temporary-certificate: "true"
    ingressClassName: public 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - hello.arepasoftware.com
    secretName: hello-tls
  rules:
  - host: hello.arepasoftware.com
    http:
      paths:
      - backend:
          serviceName: hello-v1-svc
          servicePort: 80
