apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jabvzla@arepasoftware.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jabvzla@arepasoftware.com
    privateKeySecretRef:
      name: letsencrypt-cluster-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
